language: r
cache: packages
pandoc_version: 2.9.2.1

addons:
  apt:
    packages:
    - ghostscript

before_script:
  - chmod +x ./_build.sh

script:
  - ./_build.sh

deploy:
  provider: netlify
  site: "rlabmanual"
  auth: ${NETLIFY_PAT}
  edge: true # opt in to dpl v2
  dir: "_book/"
