# Paired Samples *t* Tests {#pst}

## Learning Objectives {#pst-learning-objectives}

After completing this lab, you should be able to do the following using R:

* Conduct paired samples *t* tests.
* Compute Cohen's *d*~z~ for paired samples.
* Create appropriate visualizations for comparisons of two paired samples.

Additionally, you should be able to do the following:

* Explain how paired samples *t* tests are similar (and distinct) from one-sample *t* tests.
* Evaluate the assumptions of paired samples *t* tests.
* Accurately interpret the results of paired samples *t* tests.
* Report the results of paired samples *t* tests in APA style.

## The Study: Weight-Loss-Related Self-Efficacy {#pst-study}

### Study Information

#### Description

Weight-loss interventions aim to support people in changing their behaviours to be healthier. This includes promoting healthy-eating and exercise. Self-efficacy is thought to be important for adopting and maintaining such behaviours. That is, people will change their behaviours if they believe they can maintain those behaviours and if they believe that changing their behaviour will help them lose weight.

Because self-efficacy is so important to the success of weight-loss interventions, some such interventions now include psychotherapy specifically aimed at improving self-efficacy. Weight-loss interventions provide instrumental support in helping participants develop a plan for eating healthful foods and engaging in regular physical activity. This has a clear and obvious benefit for self-efficacy. The current study will examine how subsequent psychotherapy further boosts self-efficacy.

#### Hypothesis

The primary hypothesis is that adding psychotherapy to a weight-loss intervention will lead to increased weight-loss self-efficacy.

### Design Plan

#### Study Design

This study will use a within-subjects (paired) design. Participants will be overweight or obese individuals recruited from the community and enrolled in a weight-loss intervention at UBCO. They will attend a group session where they are provided general information about healthy eating, and physical activity. They will then have one-on-one interviews with a nutritionist to help them build meal plans that fit their budgets and lifestyles. Following the interviews, the nutritionist will ask participants to complete measures of weight-loss self-efficacy (WLSE). Participants will then meet with a trained psychotherapist who will work with the participants to identify potential barriers to their success and develop strategies for overcoming those barriers. After psychotherapy, participants will be asked to complete the same measure of WLSE.

#### Measures

Weight-loss-related behaviour self-efficacy will be measured using the scale proposed by @wlse. This scale has four items, measured on an 11-point scale ranging from 0% (*Not at All Confident*) to 100% (*Completely Confident*). The scale is relatively new; however, it has demonstrated strong psychometric properties in a large sample drawn from a population that is similar to the population used in the current study [@wlse].

#### Analytic Strategy

We will conduct a directional paired samples *t* test of the null hypothesis that average change in WLSE in the population is less than or equal to zero. Significance will be based on the traditional $\alpha$ = .05.

#### Sample Size and Power Analysis

We want to be able to detect a difference of 10 points on the WLSE measure. This measure had a *SD* = 21.44 in a large sample from a similar population [@wlse]. Assuming the same *SD* in our sample, a 10-point change translates to Cohen's *d*~z~ = 0.47. To achieve 95% power with a population effect of that size requires a sample of *N* = 50.4. We are therefore aiming for a sample of *N* = 51.

## Data Collection {#pst-data}

<form>
  <p>How confident are you that you can **lose weight...**</p>
  <table>
    <tr>
      <td>
        <label for="wlse_1">...even if you need a long time to develop the necessary routines?</label>
      </td>
      <td>
        <select id="wlse_1" name="wlse_1">
          <option value="NA">(Select an Option)</option>
          <option value="0">0% (Not at all Confident)</option>
          <option value="10">10%</option>
          <option value="20">20%</option>
          <option value="30">30%</option>
          <option value="40">40%</option>
          <option value="50">50%</option>
          <option value="60">60%</option>
          <option value="70">70%</option>
          <option value="80">80%</option>
          <option value="90">90%</option>
          <option value="100">100% (Completely Confident)</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>
        <label for="wlse_2">...even if you have to try several times before it works?</label>
      </td>
      <td>
        <select id="wlse_2" name="wlse_2">
          <option value="NA">(Select an Option)</option>
          <option value="0">0% (Not at all Confident)</option>
          <option value="10">10%</option>
          <option value="20">20%</option>
          <option value="30">30%</option>
          <option value="40">40%</option>
          <option value="50">50%</option>
          <option value="60">60%</option>
          <option value="70">70%</option>
          <option value="80">80%</option>
          <option value="90">90%</option>
          <option value="100">100% (Completely Confident)</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>
        <label for="wlse_3">...even if you have to rethink your entire way of losing weight?</label>
      </td>
      <td>
        <select id="wlse_3" name="wlse_3">
          <option value="NA">(Select an Option)</option>
          <option value="0">0% (Not at all Confident)</option>
          <option value="10">10%</option>
          <option value="20">20%</option>
          <option value="30">30%</option>
          <option value="40">40%</option>
          <option value="50">50%</option>
          <option value="60">60%</option>
          <option value="70">70%</option>
          <option value="80">80%</option>
          <option value="90">90%</option>
          <option value="100">100% (Completely Confident)</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>
        <label for="wlse_4">...even if you have to make a detailed plan?</label>
      </td>
      <td>
        <select id="wlse_4" name="wlse_4">
          <option value="NA">(Select an Option)</option>
          <option value="0">0% (Not at all Confident)</option>
          <option value="10">10%</option>
          <option value="20">20%</option>
          <option value="30">30%</option>
          <option value="40">40%</option>
          <option value="50">50%</option>
          <option value="60">60%</option>
          <option value="70">70%</option>
          <option value="80">80%</option>
          <option value="90">90%</option>
          <option value="100">100% (Completely Confident)</option>
        </select>
      </td>
    </tr>
  </table>
</form>

## Lab Report Instructions {#pst-assignment}

### R Script

1. Calculate participants' mean scores on the 5-item WLSE measure. Do this separately for the two measurement occasions.
1. Calculate *M* and *SD* for the pre- and post-psychotherapy means, and *M*, *SD*, skew, and kurtosis of the difference scores.
1. Use `t.test()` to conduct a paired *t* test of the null hypothesis that average pre-to-post change in WLSE scores is less than or equal to zero.
1. Compute Cohen's *d*~z~ for the change in WLSE scores.
1. Produce a histogram of the WLSE difference scores.
1. Produce a Q--Q plot of the WLSE difference scores.
1. Conduct a Shapiro--Wilk test on the difference scores.
1. Produce a boxplot of pre- and post-psychotherapy WLSE scores.

### Results

Write a 1--2 paragraph Results section that reports the results of your analyses. Include the following:

* *M* and *SD* of WLSE at each measurement occasion.
* Results of the *t* test, the minimally sufficient set of statistics for constructing the test.
* Standardized effect size (i.e., Cohen's *d*~z~) with associated confidence interval.
* Results of your assessment of the assumption of normality, including the Shapiro--Wilk test and other statistics you used to make inferences about the distribution of scores in the population.
* Appropriate figure visualizing scores at pre- and post-intervention. This figure should be referenced in the text of the results.

### Discussion Questions

1. Does this study support the primary hypothesis? Restate the hypothesis in plain language as part of your answer.
1. What is one potential source of bias that could affect how these results are interpreted? That is, in addition to the theoretical mechanism proposed in the introduction to the study, what else could account for the presence or absence of the effects you observed?
1. Given the results of this study, is it safe to conclude that adding psychotherapy will lead to better health outcomes for participants of weight-loss interventions? Identify what this study does not tell us that we would need to know to make strong conclusions in this regard.
