# Independent-Samples *t* Tests {#ist}

## Learning Objectives {#ist-learning-objectives}

After completing this lab, you should be able to do the following using R:

* Conduct both Student's and Welch's independent samples *t* tests.
* Compute Cohen's *d* by conversion from the test statistic using `psych::t2d()`.
* Create appropriate visualizations for comparisons of two independent samples (as described in the assignment instructions).
* Produce a single figure with subplots for each level of a grouping variable using `ggplot2::facet_wrap()`.
* Calculate group-level descriptive statistics using `by()` and `describe()`.

Additionally, you should be able to do the following:

* Evaluate the assumptions of independent samples *t* tests.
* Explain the difference between Student's *t* tests and Welch's *t* tests.
* Accurately interpret the results of independent samples *t* tests.
* Report the results of independent samples *t* tests in APA style.

## The Study: Social Identity {#ist-study}

### Study Information

#### Description

People desire positive social identities. A positive social identity is achieved when the social groups to which one belongs (i.e., the "ingroups") are perceived as favourable to the social groups to which they do not belong (i.e., the "outgroups"). Such positive social identities are most often fostered by favouring ingroup members, rather than by devaluing outgroups. As such, people tend to feel positively towards those they see as part of their ingroup.

The desire for a positive social identity can lead to discrimination when positive feelings are reserved for one's ingroup. However it can also promote acceptance of diversity. Preserving positive social identities requires accepting diversity within one's social groups. As such, broadly defining one's ingroup can foster a greater acceptance of diversity. Therefore, encouraging the adoption of broad social groups has been proposed as a means of combatting discrimination.

Of course changing how people define their ingroup is difficult. It can occur when one changes social groups, such as when one moves to a new community, makes new friends, or changes political parties. More often, however, broadening one's ingroup is accomplished by strengthening ties with existing groups. That is, rather than changing the social groups to which they belong, people are more likely to change which social groups they see as important to their social identities.

This study will examine one mechanism by which people determine the importance of social groups to their social identities: perceived social group threat. Research has demonstrated that people strengthen ties to social groups when they perceive those groups as threatened in some way. This was evident in the aftermath of the 9/11 attacks on the United States. Many US citizens felt a threat to their American social identity. This led to a dramatic outpouring of displays of patriotism, such as flying the US flag on one's property.

This study will investigate a similar effect using a Canadian sample. Although several studies have demonstrated this effect, there is value in replicating these findings. Much of this research has been conducted using US samples, and although Canada and the US are similar in many ways, their political climates are distinct. Additionally, many of the foundational studies demonstrating this effect were conducted in the early 2000s and before; since then, the political climate in both Canada and the US has changed. For example, political convictions are more rigid than they were. These factors could mean that the effects observed among Americans in these foundational studies will be different than what can be expected among Canadians today.

#### Hypothesis

It is expected that Canadians who are primed to perceive a foreign threat to Canadian social identity will place higher importance on national identity than those who are primed to perceive a domestic threat to Canadian social identity.

### Design Plan

#### Study Design

This study will employ an experimental design adapted from experiment three of @davies2008. Participants will read a brief newspaper article describing either a foreign or domestic event that could be perceived as threatening to Canadians. They will then complete a measure of national identity. Participants will be recruited at in-person public events throughout the Okanagan during the summer. Research assistants will operate tables at events throughout the summer. For completing the study, participants will be offered $5.00 food vouchers redeemable at participating vendors at the event. Recruitment will continue until sufficient data are obtained or until the summer's end.

Individuals must be at least 18-years-old and Canadian citizens to be eligible to participate.

#### Measures

National identity will be measured with items adapted[^3] from @davies2008. They will be measured on a 7-point Likert-type scale ranging from 1 (*not at all*) to 7 (*completely*).

1. Do you identify with being Canadian?
1. Is being Canadian important to you?
1. Are you proud to be a Canadian?
1. Do you think of yourself as a Canadian?

Participant scores will be averaged across these four items to create a composite measure of national identity.

[^3]: The questions are identical to those used by @davies2008 except "Canadian" replaces "American" in all instances.

#### Analytic Strategy

A directional Welch's *t* test will be conducted with the alternative hypothesis that national identity is higher in the foreign threat condition. Significance will be inferred using the traditional $\alpha$ = .05.

#### Sample Size and Power Analysis

We plan to recruit 254 participants divided evenly into the two experimental conditions. This will provide 95% power to detect an effect if the effect size in the population is *d* = 0.414.

@davies2008 reported mean national identities of 5.57 and 4.99 for participants who read about foreign and domestic threats, respectively. This amounts to a raw difference of 0.58 on the scale of 1 to 7. Because the *SD*s for national identity were not reported, we cannot know the standardized effect size for this effect. We therefore based our effect size calculation on an assumed pooled *SD* of 1.4. Under this assumption, a raw effect of 0.58 translates to *d* = 0.414.

## Lab Report Instructions {#ist-assignment}

Prepare an R script and written report presenting the results of the analysis described in the analytic strategy.

### R Script

Your R script should be reproducible and free of errors. It should contain syntax to do the following:

* Import the data and convert the "condition" variable to a factor.
* Calculate participant mean scores on the 4-item national identity measure.
* Compute descriptive statistics, including *M*, *SD*, skew, and kurtosis of participants' mean national identity. Do this separately for each level of the experimental manipulation. Use `by()` and `describe()` to do this in a single step.
* Conduct Shapiro--Wilk tests of normality for the distributions of national identity in each of the two conditions.
* Compute a Welch's *t* test as described in the analytic strategy.
* Calculate the corresponding Cohen's *d* effect size for the *t* test.

### Results

The Results section should include the following:

* Total participants in each experimental condition (note that the actual number of participants might differ from the planned number of participants in the study preregistration).
* *M* and *SD* of national identity for each experimental group.
* Results of the null-hypothesis significance test and corresponding standardized effect size with its associated confidence interval.
* Description of efforts to diagnose problems with statistical assumptions and data distributions.
* A figure visualizing mean national identity in each of the two groups and error associated with that measurement. The figure should be referenced in the text of the results section.
    * For example, boxplot, points with error bars, barchart with error bars.
    * If you use error bars, indicate what they represent in the note to the figure.

### Discussion Questions

Provide short answer responses to the following:

* Provide a statement of support or nonsupport for your primary hypothesis.
* Provide an interpretation of the results. Consider both the theory under investigation and the design of the study. Other than the proposed theoretical mechanism, what design or statistical issues could bias the results?
* Canadian adults are the implied population of interest in this study. Given the sampling design, how well does this sample represent that population? How does that affect the interpretation of these results?
* What is an implication of this research for future research, programs, or policy?
