# Univariate ANOVA {#anova}

## Learning Objectives {#anova-learning-objectives}

After completing this lab, you should be able to do the following using R:

* Conduct univariate ANOVA omnibus tests.
* Perform pairwise comparisons with corrections for familywise error.
* Specify and test planned contrasts.

Additionally, you should be able to do the following:

* Report the results of ANOVAs with pairwise comparisons or planned contrasts in APA style.
* Interpret the results of the aforementioned tests.

## The Study: Cognitive Processing and Substance Use {#aov-study}

### Study Information

#### Description

Cannabis can harm adolescent development and lead to later substance use problems. Unfortunately, programs aimed at reducing cannabis use in adolescents have been largely ineffective. A more recent approach that has shown promise is to implement programs that target individuals who are at the greatest risk of using cannabis.

What factors put adolescents at risk of cannabis use? One theory is the acquired preparedness model (APM). According to the APM, differences in personality affect learning. Learning then affects choices about cannabis use [@monti2001]. That is, some personality traits predispose individuals to developing more positive associations with substance use. There are several personality traits thought to be related to developing more positive associations with cannabis, including negative thinking, anxiety sensitivity, impulsivity, and sensation seeking. The scope of the current study is limited to just sensation seeking.

Individuals high in sensation seeking have an affinity for stimulating and novel experiences. Prior research has shown that sensation seeking is associated with a greater risk for developing alcohol-related problems [@schlauch2015] and with adolescent hallucinogen use [@krank2011]. Although research into personality and cannabis use initiation is limited, the available research suggests sensation seeking is related to future cannabis use in adolescents [@pilin2022]. The current study aims to add to the evidence demonstrating this association.

#### Hypotheses

It is hypothesized that sensation seeking will be associated with cannabis use in adolescents. Specifically, adolescents who report more recent cannabis use will report higher average sensation seeking scores compared to those who report less recent cannabis use or no cannabis use at all.

### Design Plan

#### Study Design

Participant will be students in grades 8--10. They will be given class time to complete an online survey.

#### Sample Size Rationale

The sample size will be based on the number of available respondents. Resource constraints limit data collection to a single school district. However, power analysis indicates that *n* = 61 participants per group would provide 95% power to detect effects of *f* = 0.25 or larger. This corresponds to a "medium" analysis of variance effect size according to Cohen [@cohen1988].

#### Measures {#aov-measures}

Cannabis use will be measured using a single-item, which asks, "when was the last time you used marijuana?" Response options for this item are: 0 (*never*), 1 (*more than a year ago*), 2 (*in the past year*), 3 (*in the past month*), 4 (*in the past week*). Because power analysis indicated the need for 61 participants per group, groups with fewer than 61 participants will be collapsed into a neighbouring group. The choice of which groups to collapse will be based on the number of participants in each group. The smallest group will be collapsed into its smallest neighbour. If, after collapsing two groups there is still a group with fewer than 61 participants, that group will be collapsed into its smallest neighbour. This process will continue until all groups have at least 61 participants.

The 23-item version of the Substance Use Risk Profile Scale (SURPS) will be used to measure personality [@woicik2009]. The SURPS has subscales for measuring four personality traits that are theoretically associated with substance use risk: hopelessness, anxiety sensitivity, impulsivity, and sensation seeking. Items are measured on a 4-point Likert type scale, with response options 1 (*strongly disagree*), 2 (*somewhat disagree*), 3 (*somewhat agree*), 4 (*strongly agree*). Items 1, 4, 7, 13, 20, and 23 will be reverse-coded.

For the purposes of this study, only the sensation seeking subscale of the SURPS will be used. Composite scores for sensation seeking will be produced by averaging each participant's responses to items 3, 6, 9, 12, 16, and 19.

<!-- Composite measures for each of the four subscales will be produced by averaging scores of the items associated with each subscale, as follows: -->

<!-- * Hopelessness: the mean of items 1, 4, 7, 13, 17, 20, 23. -->
<!-- * Anxiety sensitivity: the mean of items 8, 10, 14, 18, 21. -->
<!-- * Impulsivity: the mean of items 2, 5, 11, 15, 22. -->
<!-- * Sensation seeking: the mean of items 3, 6, 9, 12, 16, 19. -->

#### Analytic Strategy

An analysis of variance (ANOVA) will be conducted to test whether sensation seeking varies significantly with cannabis use. Consecutive contrasts will be conducted such that sensation seeking will be compared between each level of cannabis use and the subsequent level of cannabis use. That is, the following comparisons will be tested:

1. more than a year ago $-$ never.
1. more than a year ago $-$ in the past year.
1. in the past year $-$ in the past month.
1. in the past month $-$ in the past week.

One-sided tests will be used, such that a result will be significant if sensation seeking is higher for participants who reported more recent cannabis use. To control for inflated error due to multiple testing, *p* values of these tests will be adjusted using the Holm method.

## Data Collection {#aov-data}

<form>
  <p>**Cannabis Use**</p>
  <table>
    <tr>
      <td>
        <label for="can">When was the last time you used marijuana?</label>
      </td>
      <td>
        <select id="can" name="can">
          <option value="NA">(Select an Option)</option>
          <option value="0">never</option>
          <option value="1">more than a year ago</option>
          <option value="2">in the past year</option>
          <option value="3">in the past month</option>
          <option value="4">in the past week</option>
        </select>
      </td>
    </tr>
  </table>
  <p>**Substance Use Risk Profile Scale (SURPS)**</p>
  <p>Indicate the extent to which you agree with the statements below.</p>
  <table>
    <tr>
      <td>1</td>
      <td>
        <label for="surps_1">I am content</label>
      </td>
      <td>
        <select id="surps_1" name="surps_1">
          <option value="NA">(Select an Option)</option>
          <option value="1">strongly disagree</option>
          <option value="2">disagree</option>
          <option value="3">agree</option>
          <option value="4">strongly agree</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>2</td>
      <td>
        <label for="surps_2">I often don't think things through before I speak.</label>
      </td>
      <td>
        <select id="surps_2" name="surps_2">
          <option value="NA">(Select an Option)</option>
          <option value="1">strongly disagree</option>
          <option value="2">disagree</option>
          <option value="3">agree</option>
          <option value="4">strongly agree</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>3</td>
      <td>
        <label for="surps_3">I would like to skydive.</label>
      </td>
      <td>
        <select id="surps_3" name="surps_3">
          <option value="NA">(Select an Option)</option>
          <option value="1">strongly disagree</option>
          <option value="2">disagree</option>
          <option value="3">agree</option>
          <option value="4">strongly agree</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>4</td>
      <td>
        <label for="surps_4">I am happy.</label>
      </td>
      <td>
        <select id="surps_4" name="surps_4">
          <option value="NA">(Select an Option)</option>
          <option value="1">strongly disagree</option>
          <option value="2">disagree</option>
          <option value="3">agree</option>
          <option value="4">strongly agree</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>5</td>
      <td>
        <label for="surps_5">I often involve myself in situations that I later regret being involved in.</label>
      </td>
      <td>
        <select id="surps_5" name="surps_5">
          <option value="NA">(Select an Option)</option>
          <option value="1">strongly disagree</option>
          <option value="2">disagree</option>
          <option value="3">agree</option>
          <option value="4">strongly agree</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>6</td>
      <td>
        <label for="surps_6">I enjoy new and exciting experiences even if they are unconventional.</label>
      </td>
      <td>
        <select id="surps_6" name="surps_6">
          <option value="NA">(Select an Option)</option>
          <option value="1">strongly disagree</option>
          <option value="2">disagree</option>
          <option value="3">agree</option>
          <option value="4">strongly agree</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>7</td>
      <td>
        <label for="surps_7">I have faith that my future holds great promise.</label>
      </td>
      <td>
        <select id="surps_7" name="surps_7">
          <option value="NA">(Select an Option)</option>
          <option value="1">strongly disagree</option>
          <option value="2">disagree</option>
          <option value="3">agree</option>
          <option value="4">strongly agree</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>8</td>
      <td>
        <label for="surps_8">It's frightening to feel dizzy or faint.</label>
      </td>
      <td>
        <select id="surps_8" name="surps_8">
          <option value="NA">(Select an Option)</option>
          <option value="1">strongly disagree</option>
          <option value="2">disagree</option>
          <option value="3">agree</option>
          <option value="4">strongly agree</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>9</td>
      <td>
        <label for="surps_9">I like doing things that frighten me a little.</label>
      </td>
      <td>
        <select id="surps_9" name="surps_9">
          <option value="NA">(Select an Option)</option>
          <option value="1">strongly disagree</option>
          <option value="2">disagree</option>
          <option value="3">agree</option>
          <option value="4">strongly agree</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>10</td>
      <td>
        <label for="surps_10">It frightens me when I feel my heartbeat change.</label>
      </td>
      <td>
        <select id="surps_10" name="surps_10">
          <option value="NA">(Select an Option)</option>
          <option value="1">strongly disagree</option>
          <option value="2">disagree</option>
          <option value="3">agree</option>
          <option value="4">strongly agree</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>11</td>
      <td>
        <label for="surps_11">I usually act without stopping to think.</label>
      </td>
      <td>
        <select id="surps_11" name="surps_11">
          <option value="NA">(Select an Option)</option>
          <option value="1">strongly disagree</option>
          <option value="2">disagree</option>
          <option value="3">agree</option>
          <option value="4">strongly agree</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>12</td>
      <td>
        <label for="surps_12">I would like to learn how to drive a motorcycle.</label>
      </td>
      <td>
        <select id="surps_12" name="surps_12">
          <option value="NA">(Select an Option)</option>
          <option value="1">strongly disagree</option>
          <option value="2">disagree</option>
          <option value="3">agree</option>
          <option value="4">strongly agree</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>13</td>
      <td>
        <label for="surps_13">I feel proud of my accomplishments.</label>
      </td>
      <td>
        <select id="surps_13" name="surps_13">
          <option value="NA">(Select an Option)</option>
          <option value="1">strongly disagree</option>
          <option value="2">disagree</option>
          <option value="3">agree</option>
          <option value="4">strongly agree</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>14</td>
      <td>
        <label for="surps_14">I get scared when I'm too nervous.</label>
      </td>
      <td>
        <select id="surps_14" name="surps_14">
          <option value="NA">(Select an Option)</option>
          <option value="1">strongly disagree</option>
          <option value="2">disagree</option>
          <option value="3">agree</option>
          <option value="4">strongly agree</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>15</td>
      <td>
        <label for="surps_15">Generally, I am an impulsive person.</label>
      </td>
      <td>
        <select id="surps_15" name="surps_15">
          <option value="NA">(Select an Option)</option>
          <option value="1">strongly disagree</option>
          <option value="2">disagree</option>
          <option value="3">agree</option>
          <option value="4">strongly agree</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>16</td>
      <td>
        <label for="surps_16">I am interested in experience for its own sake even if it is illegal.</label>
      </td>
      <td>
        <select id="surps_16" name="surps_16">
          <option value="NA">(Select an Option)</option>
          <option value="1">strongly disagree</option>
          <option value="2">disagree</option>
          <option value="3">agree</option>
          <option value="4">strongly agree</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>17</td>
      <td>
        <label for="surps_17">I feel that I'm a failure.</label>
      </td>
      <td>
        <select id="surps_17" name="surps_17">
          <option value="NA">(Select an Option)</option>
          <option value="1">strongly disagree</option>
          <option value="2">disagree</option>
          <option value="3">agree</option>
          <option value="4">strongly agree</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>18</td>
      <td>
        <label for="surps_18">I get scared when I experience unusual body sensations.</label>
      </td>
      <td>
        <select id="surps_18" name="surps_18">
          <option value="NA">(Select an Option)</option>
          <option value="1">strongly disagree</option>
          <option value="2">disagree</option>
          <option value="3">agree</option>
          <option value="4">strongly agree</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>19</td>
      <td>
        <label for="surps_19">I would enjoy hiking long distances in wild and uninhabited territory.</label>
      </td>
      <td>
        <select id="surps_19" name="surps_19">
          <option value="NA">(Select an Option)</option>
          <option value="1">strongly disagree</option>
          <option value="2">disagree</option>
          <option value="3">agree</option>
          <option value="4">strongly agree</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>20</td>
      <td>
        <label for="surps_20">I feel pleasant.</label>
      </td>
      <td>
        <select id="surps_20" name="surps_20">
          <option value="NA">(Select an Option)</option>
          <option value="1">strongly disagree</option>
          <option value="2">disagree</option>
          <option value="3">agree</option>
          <option value="4">strongly agree</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>21</td>
      <td>
        <label for="surps_21">It scares me when I'm unable to focus on a task.</label>
      </td>
      <td>
        <select id="surps_21" name="surps_21">
          <option value="NA">(Select an Option)</option>
          <option value="1">strongly disagree</option>
          <option value="2">disagree</option>
          <option value="3">agree</option>
          <option value="4">strongly agree</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>22</td>
      <td>
        <label for="surps_22">I feel I have to be manipulative to get what I want.</label>
      </td>
      <td>
        <select id="surps_22" name="surps_22">
          <option value="NA">(Select an Option)</option>
          <option value="1">strongly disagree</option>
          <option value="2">disagree</option>
          <option value="3">agree</option>
          <option value="4">strongly agree</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>23</td>
      <td>
        <label for="surps_23">I am very enthusiastic about my future.</label>
      </td>
      <td>
        <select id="surps_23" name="surps_23">
          <option value="NA">(Select an Option)</option>
          <option value="1">strongly disagree</option>
          <option value="2">disagree</option>
          <option value="3">agree</option>
          <option value="4">strongly agree</option>
        </select>
      </td>
    </tr>
  </table>
</form>

## Lab Report Instructions {#aov-assignment}

### R Script

Produce the following in R:

1. Load the required packages: `psych`, `ggplot2`, `tidyr`, and `emmeans`.
1. Reverse code the appropriate items of the SURPS.
1. Use `rowMeans()` to calculate mean scores for each participant on each of the four SURPS subscales.
1. Convert `cannabis_use` to a factor collapsing levels of with fewer than 61 participants as described in the [previous section](#aov-measures).
1. Produce *M* and *SD* sensation seeking scores at each level of cannabis use (after collapsing the levels as needed).
1. Use `ggplot()` to produce a boxplot with cannabis use on the x axis and sensation seeking on y axis. Use `geom_jitter()` to plot each participants' score overtop of the boxplots.
<!-- 1. Use `pivot_longer()` to lengthen the data frame such that there is a column for subscale and another column for score on that subscale. -->
<!-- 1. Use `ggplot()` with the lengthened data frame to produce a boxplot with cannabis use on the x axis and subscale score on the y axis. Use `geom_jitter()` to plot the data over to of the boxplot. Use `facet_wrap()` to create separate facets for each SURPS subscale. -->
1. Conduct ANOVA and pairwise comparisons
    a. Use `aov()` to produce a model predicting hopelessness from cannabis use.
    a. Use `summary()` to inspect the results.
1. Conduct planned comparisons.
    a. Use `emmeans::emmeans()` to produce estimated marginal means. You will need to specify values for the arguments `object`, `specs`.
    a. Use `emmeans::contrast()` to conduct the contrasts described in the analytic strategy. See `vignette(topic = "comparisons", package = "emmeans")`.
    a. Use `emmeans::eff_size()` to produce Cohen's *d* effect sizes for the contrasts.

### Results

Write a Results section, consistent with APA style, that includes the following:

* Results of the ANOVA.
* Results of the planned comparisons.
* The plot you produced.

### Discussion Questions

Provide short answer responses to the following prompts:

* Provide a statement of support or nonsupport for your hypothesis. Refer to the results of both the omnibus ANOVA test and the planned comparisons in your response.
* The design plan described how levels of cannabis use would be collapsed if the groups were too small to provide adequate statistical power. Do you think that collapsing levels of cannabis use was adequately justified? Why or why not? How might collapsing levels of cannabis use have affected your results?
* Describe one limitation of this study. How could the limitation you identified be addressed in future research?
<!-- * The cannabis use variable was measured on an ordinal scale. A different analytic strategy would be to treat cannabis use as a continuous variable and conduct correlation tests between cannabis and the different personality traits. What are the strengths and weaknesses of using correlations compared to ANOVA? -->
